//参数代码
var conf = {
    "path": "0",
    "census": "1",
    "deny": "0",
    "vdef": "10",
    "vadd": "10",
    "cache": "86400",
    "adth1": "分享好友后获得+10次的刷新机会<br><br>提示朋友打开才管用呦！<br><img src=\"images\/here.png\" style=\"width:90%;margin-top:13px;border-radius:5px;\">",
    "adthe": "分享好友后获得+10次的刷新机会<br><br>提示朋友打开才管用呦！",
    "title": ["QQ收藏"],
    "topad": "",
    "sInfo": "没有观看次数了！\r\n\r\n①请复制转发到Q群 增加观看次数\r\n\r\n②每有一人打开你就增加10次\r\n\r\n③没有人打开不增加次数",
    "sText": "给大家分享个看篇的好东西@兄弟萌快上车！！ ###",
    "sEnd": "复制成功,返回QQ,粘贴发送到Q群吧",
    "shu": [""],
    "tongji": "",
    "ready": "",
    "btn2": "最新APP-点这下载",
    "url2": ["https://xq78.cn"],
    "btn3": "VIP线路高清原创速度快秒打开",
    "url3": ["https://www.qq.com/"],
    "btn4": "点 这 里 进 QQ 群 无 限 看",
    "url4": ["https://www.qq.com/"],
    "videos": ["./video.php"],
    "mobile": "0"
};
